## My first Linear neuron

In [2]:
import torch
import torch.nn as nn

In [3]:
## Inputs
torch.manual_seed(42)
inputs = torch.tensor([1.0,2.0,3.0])


In [4]:
neuron = nn.Linear(in_features=3,out_features=1)

In [5]:
output = neuron(inputs)

In [6]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [8]:
## Verify the output
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [9]:
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)